In [7]:
import torch

data=[[1,2],[3,4]]
x_data=torch.tensor(data)
print(x_data)

tensor=x_data

tensor[:, 1] = 0
print(tensor)


y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

print(y1)
print(y2)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 0],
        [3, 0]])
tensor([[1, 3],
        [3, 9]])
tensor([[1, 3],
        [3, 9]])


In [9]:
tensor=x_data

tensor[:, 1] = 0
print(tensor)

# 두 텐서 간의 행렬 곱(matrix multiplication)
# ``tensor.T``는 텐서의 전치 행렬을 의미
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

print(y1)
print(y2)

tensor([[1, 0],
        [3, 0]])
tensor([[1, 3],
        [3, 9]])
tensor([[1, 3],
        [3, 9]])
